plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs56.github.io # the base hostname & protocol for your site
baseurl: /f19  # the subpath of your site, e.g. "/blog"


include:
  - _pages
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
  - .bundle

course: "CS56"
qtr: "F19"
qxx: "f19"
quarter: "Fall 2019"
piazza_url: https://piazza.com
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=tbd
github_org_name: ucsb-cs56-f19
github_org_url: https://github.com/ucsb-cs56-f19

ta_list: "Scott and Zachary"
ta_list_full: "Scott Chow and Zachary Sisco"
mentors_list: "Daniel, George, and Meredith"
discussion_section_times: "5pm,&nbsp;6pm,&nbsp;7pm"

github_url: https://github.com/ucsb-cs56/f19
mentor_url: https://ucsb-cs56-pconrad-mentors.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"


sections: "5pm,&nbsp;6pm,&nbsp;7pm"

start_week: 0
start_date: 2019-09-22
num_weeks: 11
extra_exam_week: true

cal_dates: >
  [
    {"label":"F19 official start date", "date":"2019-09-22" },
    {"label":"F19 1st day of instruction", "date":"2019-09-26" },	
    {"label":"Univ Holiday", "date":"2019-11-11" },
    {"label":"Univ Holiday", "date":"2019-11-28" },
    {"label":"Univ Holiday", "date":"2019-11-29" },
    {"label":"F19 instruction ends", "date":"2019-12-06" },
    {"label":"F19 finals start", "date":"2019-12-07" },
    {"label":"F19 finals end", "date":"2019-12-13" },
    {"label":"F19 qtr ends", "date":"2019-12-13" }
  ]

hwk_drop_lowest: three

legacy_wiki_name: 56wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/56wiki" 


hfj_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfj/HFJ_Chapter_"
hfdp_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfdp/HFDP_Chapter_"

kramdown:
   parse_block_html: true


exclude:
   - vendor
   - _exam/e02/cs56_m16_e02/code
   - _exam/e01/cs56_f16_e01/code


timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
   - /static/js/select_section.js

